Jc 601 book catalog new design
saritasa-nest/camp-js-2024-kirill-fatykov pull request #1
Opened 2024-07-05 05:25 UTC by FatykovKirill

2024-07-09 08:53 UTC, artem-sotnichenko-saritasa commented
I'll start with design review. Code review a bit later.

1. Please make your markup fluid. That means that your app should change markup not only on specific media queries, but for every screen width.

Check the video example. It has display grid applied this way: show maximum amount of cards with minimum with of card=180px. So it looks good on any screen size
In your app, there are white space on the sides, when changing page size.

https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/98300391/b34aacc4-68ef-45a8-b064-b3744d723634

It explained in the article I listed with CSS lecture in slack.

2024-07-09 09:13 UTC, shalomich commented
<img width="550" alt="image" src="https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/75197645/eeb80641-ce18-4c08-9a56-e73e7686f430">

2024-07-09 09:14 UTC, shalomich requested changes

2024-07-09 09:14 UTC, shalomich commented on apps/vanilla/src/pages/index.css
> +  font-size: var(--font-size-md);
Typographies are usually used in designs, which can be reused, so it is better to put them in separate classes

<img width="403" alt="image" src="https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/75197645/c04c94ed-7e14-4fa2-92c3-fdaa47c25fe3">
<img width="274" alt="image" src="https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/75197645/b008cff0-0046-48eb-8751-c22f8dd38e6c">

2024-07-09 09:14 UTC, shalomich commented on apps/vanilla/src/pages/index.css
> +  padding-bottom: 76px;
I don't see such a big pudding in the designs

2024-07-09 10:51 UTC, SofyaKirillova requested changes

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +.app__logo > a {
Let's create a separate class for this. This will improve readability

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +  color: black;
Let's put it in a variable. Please use rgx or hexadecimal

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +  --border: rgb(0 0 0 / 15%);
Let's improve the name, now it's not clear from the name that they store color, size or something else

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +  /* Spaces */
Let's add `--space-base: 4px`

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +  --space-2: 8px;
```suggestion
  --space-2: calc(--space-base * 2);
```

If we change `--space-base`, we won't need to change other variables.

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +  --border-radius-24: 24px;
```suggestion
  --border-radius-sm: 4px;
  --border-radius-md: 16px;
  --border-radius-lg: 24px;
```

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/img/arrow-down.png
It is better to use icons in svg format, as they are smaller in size

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +.sidebar__checkbox-container > input {
Let's create a separate class for this

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +  height: 20px;
I think it can be put into a separate variable

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +.footer__nav a {
I think it can be put into a separate variable

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +@media screen and (max-width: 1921px) {
Let's round up the value

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +@media screen and (max-width: 1281px) {
Let's round up the value

2024-07-09 10:51 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +          <div class="footer__year">© 2023</div>
```suggestion
          <div class="footer__year">&copy; 2023</div>
```

2024-07-09 10:55 UTC, SofyaKirillova requested changes
![image](https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/108254953/eb4f17c7-c1c0-47e4-8ac1-ffe213920967)

The icon overlaps the text
Checkbox isn't centered

![image](https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/108254953/eca49174-f1c1-4bf4-b604-6c0dd75912f5)

No indentation

![image](https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/108254953/ac64bd2e-f18d-4de8-9d01-cd271ecf30a7)
Part of the image is visible between the checkbox and the year

2024-07-11 12:16 UTC, SofyaKirillova requested changes

2024-07-11 12:16 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +							<select class="sidebar__select typography typography__body" name="sort-select" id="sort-select">
![image](https://github.com/saritasa-nest/camp-js-2024-kirill-fatykov/assets/108254953/5b599c41-57ea-406a-a054-15141c709b51)

Large indentation

2024-07-11 12:16 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +						<form>
Why is only select wrapped in a form?

2024-07-11 12:16 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +						<input class="sidebar__search typography typography__body" type="text" name="search" id="search" placeholder="e.g. “Refactoring”">
Don't use id, please

2024-07-11 12:16 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +						<input class="sidebar__search typography typography__body" type="text" name="search" id="search" placeholder="e.g. “Refactoring”">
Use the search type

2024-07-22 05:33 UTC, shalomich approved these changes

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/index.html
> +	<div class="container content-flex-container">
It looks like your two classes are not being reused. Then why was it necessary to divide into two BEM blocks?

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/index.html
> +	<div class="container content-flex-container">
The prefix `flex` looks redundant. Its implementation detail is not important to us, but rather the scope of application is important. Just for example: `main-container`, `books-container`, `footer-container`

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/css/typography.css
> +}
`__` is the designation of the `BEM element`. But `_` (or `--`)  is the designation of the` BEM modificator`. https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

```suggestion
.typography_logo {
	font-size: var(--font-size-xl);
	line-height: 24px;
	font-weight: 700;
}

.typography_subtitle {
	font-size: var(--font-size-lg);
	line-height: 24px;
	font-weight: 600;
	text-transform: uppercase;
}

.typography_body {
	font-size: var(--font-size-xl);
	line-height: 32px;
	font-weight: 400;
}

.typography_body-small {
	font-size: var(--font-size-md);
	line-height: 24px;
	font-weight: 500;
}
```

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/index.html
> +			<h1 class="books-logo main-header__logo typography__logo">📚 Books app</h1>
Rather than a `books-logo`, but an `app-logo`. And then the logo is a image, but here it's more like a `title`

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/index.html
> +		<footer class="main-footer">
The `main` prefix looks redundant for footer because because he is alone and there are no `additional`

```suggestion
		<footer class="footer">
```

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/index.html
> +				<nav class="main-footer__nav"><a class="main-footer__nav_link typography__body"
I assume that this is a typo and you did not mean the BEM modifier `main-footer__nav_link`, because modifiers are used in conjunction with a BEM block or BEM element. Example: 
<nav class="main-footer__nav">
<nav class="main-footer__nav main-footer__nav_link">

```suggestion
				<nav class="main-footer__nav"><a class="main-footer__nav-link typography__body"
```

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/css/components.css
> +	margin: 0 auto;
It is better to use `flex` for centering https://learn.javascript.ru/css-center#tsentrirovanie-s-ispolzovaniem-modeli-flexbox

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/css/components.css
> +.container {
```suggestion
.main-container {
```

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/css/components.css
> +.main-header {
```suggestion
.header {
```

2024-07-22 05:33 UTC, shalomich commented on apps/vanilla/src/pages/bookCatalog/css/components.css
> +.content {
Please use more specific name.

2024-07-25 06:25 UTC, SofyaKirillova approved these changes

2024-07-25 06:25 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +	--heading-color-3: rgb(176 224 230 / 100%);
```suggestion
	--heading-color-1: rgb(255 215 0);
	--heading-color-2: rgb(233 150 122);
	--heading-color-3: rgb(176 224 230);
```

2024-07-25 06:25 UTC, SofyaKirillova commented on apps/vanilla/src/pages/bookCatalog/css/components.css
> +	height: var(--space-32);
This is the height to use `--space-32` isn't correct

2024-07-25 06:25 UTC, SofyaKirillova commented on apps/vanilla/src/pages/bookCatalog/index.html
> +		<footer class="main-footer">
GitHub should be located on the right
Also by design there is an space at the bottom
![image](https://github.com/user-attachments/assets/1ddbbe79-ad79-4be5-81a2-dcf48af89dad)

2024-07-26 08:25 UTC, merged