Jc 641 initialize anime app and table view
saritasa-nest/camp-js-2024-kirill-fatykov pull request #3
Opened 2024-07-25 10:56 UTC by FatykovKirill

2024-07-26 09:29 UTC, daoduong-saritasa requested changes
Please don't disable `jsdoc/require-jsdoc` rule, we have it for a reason :). Review [this wiki section](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#comments--documentation) and update all places that you disable this rule with docs. Make sure it has the right format also.

2024-07-26 09:29 UTC, daoduong-saritasa commented on apps/angular/src/app/features/replaceEmptyString.pipe.ts
> +	public transform(string: string | null, replaceValue: string): string {
Can we extend this to handle more nullish value other than string such as `null`, `undefined`, `NaN`. And we should have default value for `replaceValue`, it would be better if we're not require to pass replace value for every use.

2024-07-26 09:29 UTC, daoduong-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	/** Get JSON from API. */
This docs doesn't mean anything, every function in this service is get json from api, try to come up with a meaningful name

2024-07-26 09:29 UTC, daoduong-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	public getAnime(): Observable<AnimeDomain[]> {
[Avoid context duplication](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-context-duplication), as anime doesn't have plural, we could use `list`.
```suggestion
	public getList(): Observable<AnimeDomain[]> {
```

2024-07-26 09:29 UTC, daoduong-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +			},
Please check out for [interceptors](https://angular.dev/guide/http/interceptors). What if later we will have dozen of api like this and we have to manually add header?

2024-07-26 09:55 UTC, DaniilMaslovSaritasa approved these changes

2024-07-26 09:55 UTC, DaniilMaslovSaritasa commented on apps/angular/src/app/anime-table/anime-table.component.html
> +      <td mat-cell *matCellDef="let anime" class="anime-table__content typography_content"> <img class="anime-table__image" src={{anime.image}} alt={anime.titleJpn}}> </td>
```suggestion
      <td mat-cell *matCellDef="let anime" class="anime-table__content typography_content"> <img class="anime-table__image" [src]="anime.image" [alt]="anime.titleJpn"> </td>
```
It is better to use property bindings than property interpolation

2024-07-26 09:55 UTC, DaniilMaslovSaritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	public displayedColumns: string[] = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'];
```suggestion
	public displayedColumns = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'] as const;
```
We prefer not to geclare the type explicitly if it is calculated by typescript.

2024-07-26 09:55 UTC, DaniilMaslovSaritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	imports: [MatTableModule, AsyncPipe, DatePipe, ReplaceEmptyStringPipe],
`changeDetection: ChangeDetectionStrategy.OnPush `
 Try to use the Angular OnPush Change Detection strategy in all components

2024-07-26 09:55 UTC, DaniilMaslovSaritasa commented on apps/angular/src/theme/typography.css
> +	font-size: 16px;
Try to use css variables for font-size

2024-07-30 07:19 UTC, daoduong-saritasa approved these changes

2024-07-30 07:19 UTC, daoduong-saritasa commented on libs/core/mappers/anime.mapper.ts
> +/** Service for mapping date. */
Wrong docs

2024-08-07 08:12 UTC, viktor-sakhno-saritasa approved these changes

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on .vscode/settings.json
> +}
I don't recommend littering the code with such things, you can add these settings personally for the user in the VS Code's user settings, not in the workspace

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	private animeService = inject(AnimeService);
Check all files for skipped readonly modifiers, pls.
```suggestion
	protected readonly animeList$: Observable<Anime[]>;

	private readonly animeService = inject(AnimeService);
```

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	public displayedColumns = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'] as const;
Also, pls, prefer to use `protected` modified instead `public`, where it is possible.
```suggestion
	protected readonly displayedColumns = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'] as const;
```

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/app.component.html
> +	<router-outlet></router-outlet>
You can use self-closing tags.
```suggestion
	<router-outlet/>
```

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on libs/core/models/anime-type.model.ts
> +export enum AnimeType{
```suggestion
export enum AnimeType {
```

2024-08-07 08:12 UTC, viktor-sakhno-saritasa commented on libs/core/models/anime.model.ts
> +	};
```suggestion
	aired: Readonly<{

		/** Start air date. */
		start: string | null;

		/** End air date. */
		end: string | null;
	}>;
```

2024-08-19 05:37 UTC, golovachev-yaroslav requested changes

2024-08-19 05:37 UTC, golovachev-yaroslav commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
>  interface Props {
It should by type instead of props.

2024-08-19 05:37 UTC, golovachev-yaroslav commented on apps/react/src/store/store.ts
> +/* eslint-disable jsdoc/require-jsdoc */
Please add jsdoc..

2024-08-19 05:37 UTC, golovachev-yaroslav commented on libs/core/dtos/genre.dto.ts
> +// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
Need to check all eslint-disable-next-line

2024-08-19 06:09 UTC, golovachev-yaroslav approved these changes

2024-08-19 08:37 UTC, violetta-klintsova commented on libs/core/models/anime-mapper.model.ts
> +	/** Mapper method for . */
Seems like you have not finished the sentence)

2024-08-19 08:37 UTC, violetta-klintsova commented on libs/core/models/anime.model.ts
> +	}>;
I would extract this into a separate model, because in larger codebases such things may as well go unnoticed and then we have a bunch of the same modes hidden inside and different approaches to data mapping.
Also, it's recommended to add an example of the data stored inside, e.g.;

`  /** Creation date (2024-05-28). */`

2024-08-19 08:37 UTC, violetta-klintsova commented on libs/core/dtos/anime.dto.ts
> +}>;
Why do you have two `PaginationDto` models? This one and a generic one

2024-08-19 08:37 UTC, violetta-klintsova commented on libs/core/dtos/anime.dto.ts
> +	/** Name title in English. */
```suggestion
	/** Anime title in English. */
```

2024-08-19 08:37 UTC, violetta-klintsova commented on libs/core/dtos/anime.dto.ts
> +	/** Name title in Japanese. */
```suggestion
	/** Anime title in Japanese. */
```

2024-08-19 09:18 UTC, violetta-klintsova commented on libs/core/mappers/anime.mapper.ts
> +		return dto.results.map((result: AnimeDto): Anime => (
The problem here is that pagination DTO is coupled with your anime mapper, but it shouldn't be.
`Pagination` is something generic, you can use it multiple times across your application, while `Anime` is not.

It would be better to have a separate mapper for pagination, which can accept a specific one (in this case mapper for a single Anime).
What I mean is that you map pagination data and inside of it you usually have a property `results`, which will be an array of DTOs (of Anime in your case), which you can map through and return an new one.

2024-08-29 06:44 UTC, merged