Jc 661 anime list managment
saritasa-nest/camp-js-2024-kirill-fatykov pull request #4
Opened 2024-08-06 06:15 UTC by FatykovKirill

2024-08-06 09:31 UTC, andrey-gazzaev requested changes

2024-08-06 09:31 UTC, andrey-gazzaev commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	private readonly results = signal<AnimeEvents>({});
Use streams instead of signals

2024-08-06 09:31 UTC, andrey-gazzaev commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +		* Select change type anime.
```suggestion
		* Handles anime type selection.
```

2024-08-06 09:31 UTC, andrey-gazzaev commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	protected selectChange(selectEvent: MatSelectChange): void {
```suggestion
	protected onTypeSelect(selectEvent: MatSelectChange): void {
```

2024-08-07 06:01 UTC, karbik-creator requested changes

2024-08-07 06:01 UTC, karbik-creator commented on libs/core/models/anime-events.model.ts
> +	} | undefined;
```suggestion
	paginator?: {

		/** Page index. */
		pageIndex: number;

		/** Page size. */
		pageSize: number;
	};
```

2024-08-08 05:29 UTC, karbik-creator commented
@FatykovKirill 
I don't see any changes, maybe you forgot to push them

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa requested changes

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	}
Let's refactor your code, so we don't need `results`, and `results$` our single source of truth. Also, let's rename it to `filters$`

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	protected onPaginatorAnime(paginatorEvent: PageEvent): void {
Let's name it `onPageChange`
You don't need to add `Anime` suffix for every handler.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	protected readonly displayedColumns = ['image', 'title_eng', 'title_jpn', 'aired__startswith', 'type', 'status'] as const;
We usually place properties first and then methods. So please move it higher in the component.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/interceptors/header.interceptor.ts
> +	* @param next - Function representing the next processing step in the interceptor chain.
Please omit `-` after params in jsdoc
```suggestion
	* @param req Outgoing HttpRequest.
	* @param next Function representing the next processing step in the interceptor chain.
```

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	private animeConfig = inject(ApiConfig);
Don't forget about `readonly`

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +	public filter(object: AnimeEvents): string {
It's a great place to write explaining jsdoc. It's not obvious what this function do.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +	public filter(object: AnimeEvents): string {
Also please don't use such generic names for function params as `object`

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +		const result: string[] = [];
I suggest using `URLSearchParams`.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +					result.push('');
You don't need to push anything in `default` case.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +					const [pageIndex, pageSize] = Object.values(value);
If I understand correctly, value has such shape `{ pageIndex: number, pageSize: number }`. Why do we need to use `Object.values()`, shouldn't we be able to just read properties?

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/query.service.ts
> +		entiresEvents.forEach(([key, value]) => {
I think you overcomplicated things. What do you think about such approach?

```ts
		const searchParams = new URLSearchParams();

		if (object.paginator != null) {
			const { pageIndex, pageSize } = object.paginator;
			searchParams.append('limit', String(pageSize));
			searchParams.append('offset', String(pageIndex * pageSize));
		}

		...

		return searchParams.toString();
```

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/anime.dto.ts
> +	/** Post creation date. */
Its a good practice to add an example of a date format in jsdoc.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/anime.dto.ts
> +	};
Let's create date range dto (and model too)

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/anime.dto.ts
> +	/** Numbers of studios. */
It's actually a list of studio IDs.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +	public fromAnimeDto(dto: PaginationDto<AnimeDto>): AnimePagination<Anime> {
You can omit `Anime` here. Because you already have `Anime` in mapper name. It's called duplication of context.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +/** Service for mapping date. */
Please fix jsdoc

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/genre.mapper.ts
> +		*/
The previous formatting was right.

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/models/anime-events.model.ts
> +export type AnimeEvents = Readonly<{
Let's name it `AnimeFilters`

2024-08-08 13:54 UTC, artem-sotnichenko-saritasa commented on libs/core/models/anime-mapper.model.ts
You don't need to create models for mappers

2024-08-09 10:31 UTC, karbik-creator requested changes

2024-08-09 10:31 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +		this.results = { ...this.results, paginator: { pageIndex: paginatorEvent.pageIndex, pageSize: paginatorEvent.pageSize } };
`updateAnimeList `is probably missing here

2024-08-09 10:31 UTC, karbik-creator commented on apps/angular/src/core/services/anime.service.ts
> +	private animeMapper: AnimeMapper = inject(AnimeMapper);
```suggestion
	private readonly animeMapper= inject(AnimeMapper);
```

2024-08-09 10:31 UTC, karbik-creator commented on apps/angular/src/core/services/anime.service.ts
> +	public getList(queryString: string | null = ''): Observable<AnimePagination<Anime>> {
According to the code, `null `never comes here. You can remove it
```suggestion
	public getList(queryString: string = ''): Observable<AnimePagination<Anime>> {
```

2024-08-12 06:51 UTC, karbik-creator requested changes

2024-08-12 06:51 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	});
As far as I remember, before this you had an implementation via submit, now it is gone and you can remove `FormGroup `and just use `FormControl`

2024-08-12 06:51 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +			...this.filter$,
```suggestion
			...this.filter$.value,
```

2024-08-12 06:51 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +		this.filter$.next({ ...this.filter$, sort: sortEvent });
```suggestion
		this.filter$.next({ ...this.filter$.value, sort: sortEvent });
```

2024-08-12 06:51 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +			...this.filter$,
Please check if your filters, sorting and pagination are working correctly

2024-08-13 02:10 UTC, artem-sotnichenko-saritasa approved these changes

2024-08-13 02:10 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +				(result: AnimeDto): Anime => ({
You can omit such types, they should be fully inferable. 
```suggestion
				result => ({
```

2024-08-18 16:56 UTC, andrey-gazzaev approved these changes

2024-08-18 16:56 UTC, andrey-gazzaev commented on apps/angular/src/app/anime-table/anime-table.component.html
> +		class="mat-elevation-z8 anime-table"
https://material.angular.io/cdk/table/api#:~:text=trackBy%3A-,TrackByFunction%3CT%3E,-Tracking%20function%20that

Looks like you forgot to use track by function

2024-08-18 16:56 UTC, andrey-gazzaev commented on libs/core/models/anime-filters.model.ts
> +	paginator?: {
```suggestion
	pagination?: {
```

2024-08-19 04:28 UTC, karbik-creator approved these changes

2024-08-19 04:28 UTC, karbik-creator commented on apps/angular/src/app/anime-table/anime-table.component.ts
> +	}
Please use `takeUntilDestroyed`

```
private readonly destroyRef = inject(DestroyRef);
takeUntilDestroyed(this.destroyRef)
```

2024-08-19 04:32 UTC, golovachev-yaroslav requested changes

2024-08-19 04:32 UTC, golovachev-yaroslav commented on libs/core/dtos/anime.dto.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
This is a not good decision to disable eslint for the whole file. Could you avoid eslint-disable?

2024-08-19 04:32 UTC, golovachev-yaroslav commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
Looks like here should be type instead of props.

2024-08-19 04:32 UTC, golovachev-yaroslav commented on apps/react/src/store/store.ts
> +/* eslint-disable jsdoc/require-jsdoc */
PLease add doc

2024-08-29 06:13 UTC, golovachev-yaroslav approved these changes

2024-08-29 06:19 UTC, merged